# ===================================================================
# Build system
# ===================================================================
[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"


# ===================================================================
# Project metadata
# ===================================================================
[project]
name = "notate"
version = "0.4.0"
description = "Notational inconsistency impacts."
readme = "README.md"
requires-python = ">=3.9"

authors = [
  { name = "Yosuke Kikuchi", email = "uo.ko.teen18@gmail.com" },
  { name = "Tadahaya Mizuno", email = "tadahaya@gmail.com" },
]

license = { text = "MIT" }

# -------------------------------------------------------------------
# Runtime dependencies
# -------------------------------------------------------------------
dependencies = [
  "numpy",
  "pandas",
  "scikit-learn",
  "tqdm",
  "matplotlib",
]

# ===================================================================
# Optional dependencies
# ===================================================================
[project.optional-dependencies]
dev = [
  "jupyterlab",
  "ipykernel",
  "black",
  "ruff",
  "isort",
  # "pytest",
]


# ===================================================================
# Tooling configuration (style/lint/type hints)
# ===================================================================

[tool.black]
line-length = 88
target-version = ["py39"]
skip-string-normalization = false

[tool.isort]
profile = "black"
line_length = 88
combine_as_imports = true
force_sort_within_sections = true

[tool.ruff]
target-version = "py39"
line-length = 88
select = ["E", "F", "W", "I", "UP", "B", "PL"]
ignore = [
  "E203",  # conflicts with Black
  "E266",  # allow multiple leading '#'
]

[tool.ruff.isort]
known-first-party = ["notate"]

[tool.mypy]
python_version = "3.9"
ignore_missing_imports = true
warn_unused_ignores = true
strict_optional = true
no_implicit_optional = true
disallow_untyped_defs = false  # staged adoption to avoid breaking runtime