#! /bin/bash

USERNAME=$(whoami)

if [ $USERNAME = "filsev" ]; then
    ROOTDIR=/mnt/local/user/yoshikai
else
    ROOTDIR=/mnt/local/HDD1/user/yoshikai
fi

LOCAL_PARDIR=$(dirname $ROOTDIR/$1)

scp -r super_miz2022y:/work/02/ga97/a97003/$1 $LOCAL_PARDIR/.