#! /bin/bash

USERNAME=$(whoami)

if [ $USERNAME = "filsev" ]; then
    ROOTDIR=/mnt/local/user/yoshikai
else
    ROOTDIR=/mnt/local/HDD1/user/yoshikai
fi

REMOTE_PARDIR=$(dirname /work/02/ga97/a97003/$1)

scp -r $ROOTDIR/$1 super_miz2022y:$REMOTE_PARDIR/.